# Generated by Django 2.2 on 2019-05-06 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pikmin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Planet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='惑星名')),
                ('name_kana', models.CharField(blank=True, max_length=80, null=True, verbose_name='惑星名カナ')),
            ],
        ),
    ]
