# Generated by Django 2.2 on 2019-05-06 12:44

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pikmin', '0002_planet'),
    ]

    operations = [
        migrations.AddField(
            model_name='planet',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='作成日'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='planet',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='更新日'),
        ),
        migrations.CreateModel(
            name='Onion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='オニオン名')),
                ('started_on', models.DateField(verbose_name='開始日')),
                ('ended_on', models.DateField(blank=True, null=True, verbose_name='終了日')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日')),
                ('planet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pikmin.Planet', verbose_name='惑星')),
            ],
        ),
    ]
